[Open in Colab](https://colab.research.google.com/drive/1c2r2gb-Tv6V-83_AUaG5nV0xa7ENT5k3)

In [0]:
# !pip freeze # requirements.txt or pipfile

In [0]:
# requirements for notebook
!pip install pandas gspread gspread-dataframe

Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (0.25.3)
Requirement already satisfied: gspread in /usr/local/lib/python3.6/dist-packages (3.0.1)
Requirement already satisfied: gspread-dataframe in /usr/local/lib/python3.6/dist-packages (3.0.3)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.6/dist-packages (from pandas) (1.17.4)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas) (2.6.1)
Requirement already satisfied: requests>=2.2.1 in /usr/local/lib/python3.6/dist-packages (from gspread) (2.21.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.6.1->pandas) (1.12.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.2.1->gspread) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.2.1->gspread) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.2.1->gspread) (1.24.3)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.2.1->gspread) (2.8)

In [0]:
import pandas as pd
import gspread
from gspread_dataframe import get_as_dataframe, set_with_dataframe
from oauth2client.client import GoogleCredentials

In [0]:
from google.colab import auth
auth.authenticate_user()

In [0]:
default_app = GoogleCredentials.get_application_default()

In [0]:
gc = gspread.authorize(default_app)

In [0]:
SPREADSHEET_NAME = 'BASE CFE'
PRIMARY_WORKSHEET = "Primary"
INPUT_WORKSHEET = "Input"
OUTPUT_WORKSHEET = 'Output'
SETUP_SPREADSHEET = False

In [0]:
if SETUP_SPREADSHEET:
  spreadsheet = gc.create(SPREADSHEET_NAME)
  spreadsheet.add_worksheet(INPUT_WORKSHEET, 1, 1)
  spreadsheet.add_worksheet(OUTPUT_WORKSHEET, 1, 1)

In [0]:
spreadsheet = gc.open(SPREADSHEET_NAME)

In [0]:
worksheet = spreadsheet.worksheet(title=PRIMARY_WORKSHEET)
worksheet_in = spreadsheet.worksheet(title=INPUT_WORKSHEET)
worksheet_out = spreadsheet.worksheet(title=OUTPUT_WORKSHEET)

In [0]:
rows = worksheet.get_all_values()
print(rows[:5])

[['Title', 'Rank', 'Views'], ['John Wick', 'A', '100000'], ['John Wick 2', 'A', '5000'], ['John Wick 3', 'A+', '124201']]

In [0]:
df = pd.DataFrame.from_records(rows)
# df.rename(columns=df.iloc[0], inplace=True)
# df.drop(df.index[0], inplace=True)
df.head()

             0     1       2
0        Title  Rank   Views
1    John Wick     A  100000
2  John Wick 2     A    5000
3  John Wick 3    A+  124201

In [0]:
# set the dataframe column names based on the first row, and dropping that first row
df = df.rename(columns=df.iloc[0]).drop(df.index[0])
df.head()

         Title Rank   Views
1    John Wick    A  100000
2  John Wick 2    A    5000
3  John Wick 3   A+  124201

In [0]:
df['By_Thousand'] = df['Views']
df.head()

         Title Rank   Views By_Thousand
1    John Wick    A  100000      100000
2  John Wick 2    A    5000        5000
3  John Wick 3   A+  124201      124201

In [0]:
df['Views'] = df['Views'].astype(int)
df['By_Thousand'] = df['Views'] * 0.001
df.head()

         Title Rank   Views  By_Thousand
1    John Wick    A  100000      100.000
2  John Wick 2    A    5000        5.000
3  John Wick 3   A+  124201      124.201

In [0]:
set_with_dataframe(worksheet_out, df)

In [0]:
input_df = get_as_dataframe(worksheet_in)
input_df.head()

         Title Rank   Views  By_Thousand
0    John Wick    A  100000      100.000
1  John Wick 2    A    5000        5.000
2  John Wick 3   A+  124201      124.201